/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualPatternsRouteImport } from './routes/visual-patterns'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as IndexRouteImport } from './routes/index'

const VisualPatternsRoute = VisualPatternsRouteImport.update({
  id: '/visual-patterns',
  path: '/visual-patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flags': typeof FlagsRoute
  '/visual-patterns': typeof VisualPatternsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flags': typeof FlagsRoute
  '/visual-patterns': typeof VisualPatternsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flags': typeof FlagsRoute
  '/visual-patterns': typeof VisualPatternsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flags' | '/visual-patterns'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flags' | '/visual-patterns'
  id: '__root__' | '/' | '/flags' | '/visual-patterns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlagsRoute: typeof FlagsRoute
  VisualPatternsRoute: typeof VisualPatternsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual-patterns': {
      id: '/visual-patterns'
      path: '/visual-patterns'
      fullPath: '/visual-patterns'
      preLoaderRoute: typeof VisualPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlagsRoute: FlagsRoute,
  VisualPatternsRoute: VisualPatternsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
